title: Nuri Uzunoğlu
email: crimeemperor@gmail.com
description: Founder & Jr. Software Engineer @ I.O.

baseurl: ""
url: "http://nuriuzunoglu.com"

author:
  fullname: Nuri Uzunoğlu
  github: nuriu
  twitter: ezhoikam
  # disqus: ezhoikam

google_analytics: 'UA-64801555-1'

# Syntax highlighting
highlightstyle: 'monokai-sublime'
styles: [agate,
        androidstudio,
        arduino-light,
        arta,
        ascetic,
        atelier-cave-dark,
        atelier-cave-light,
        atelier-dune-dark,
        atelier-dune-light,
        atelier-estuary-dark,
        atelier-estuary-light,
        atelier-forest-dark,
        atelier-forest-light,
        atelier-heath-dark,
        atelier-heath-light,
        atelier-lakeside-dark,
        atelier-lakeside-light,
        atelier-plateau-dark,
        atelier-plateau-light,
        atelier-savanna-dark,
        atelier-savanna-light,
        atelier-seaside-dark,
        atelier-seaside-light,
        atelier-sulphurpool-dark,
        atelier-sulphurpool-light,
        codepen-embed,
        color-brewer,
        dark,
        darkula,
        default,
        docco,
        far,
        foundation,
        github,
        github-gist,
        googlecode,
        grayscale,
        gruvbox-dark,
        gruvbox-light,
        hopscotch,
        hybrid,
        idea,
        ir_black,
        kimbie.dark,
        kimbie.light,
        magula,
        mono-blue,
        monokai,
        monokai-sublime,
        obsidian,
        paraiso-dark,
        paraiso-light,
        pojoaque,
        purebasic,
        qtcreator_dark,
        qtcreator_light,
        railscast,
        rainbow,
        school-book,
        solarized-dark,
        solarized-light,
        sunburst,
        tomorrow,
        tomorrow-night,
        tomorrow-night-blue,
        tomorrow-night-bright,
        tomorrow-night-eightie,
        vs,
        xcode,
        xt256,
        zenburn]

# Build settings
highlighter: null
markdown: kramdown
