title: Blog - Nuri Uzunoğlu
description: "Nuri Uzunoğlu // Yazılım Mühendisliği Öğrencisi Kişisel Web Sayfası."
baseurl: ""
url: "http://nuriuzunoglu.com"

username: Nuri Uzunoğlu
user_title: Yazılım Mühendisi
email: dev@nuriuzunoglu.com
github_username: nuriu
hackerrank_username: nuriu
linkedin_username: nuriuzunoglu
stackoverflow_userid: 6423537
disqus_username: Ezhoikam

google_analytics: UA-64801555-1

markdown: kramdown
highlighter: rouge
permalink: /:title/

compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

links:
  - title: anasayfa
    url: /
  - title: yazılar
    url: /yazilar
  - title: seriler
    url: /seriler
  - title: etiketler
    url: /etiketler
  - title: hakkımda
    url: /hakkimda

projects:
  - name: iom (2018 Ç2) (c++, vulkan, glm, cmake)
    url: https://github.com/nuriu/iom
  - name: ajanda (2017 Ç4) (typescript, angular, .net core, postgresql)
    url: https://github.com/nuriu/ajanda
  - name: oyun geliştirme yolu (2017 Ç3-Ç4)
    url: https://github.com/nuriu/oyun-gelistirme-yolu
  - name: hapicpp (2017 Ç1) (c++, jsoncpp, restclient-cpp, cmake)
    url: https://github.com/nuriu/hapicpp
  - name: docendodiscimus (2016 Ç4) (c#, asp.net mvc, wcf)
    url: https://github.com/nuriu/docendodiscimus
  - name: mezbele (2016 Ç4) (c#, asp.net mvc, materialize)
    url: https://github.com/nuriu/mezbele
  - name: filmoneri (2016 Ç4) (typescript, electron, sqlite)
    url: https://github.com/nuriu/filmoneri
  - name: haber (typescript, electron, semantic ui)
    url: https://github.com/nuriu/haber
  - name: blog (ruby, ruby on rails)
    url: https://github.com/nuriu/nuriu.github.io
